# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache

    # At the moment, sbt 0.13.5 is preinstalled in Travis VM image,
    # which fortunately corresponds to current scalaz settings.
    # The line below can be used to cache a given sbt version.
    # - $HOME/.sbt/launchers/0.13.x

    # The line below is used to cache the scala version used by the build
    # job, as these versions might be replaced after a Travis CI build
    # environment upgrade (e.g. scala 2.11.2 could be replaced by scala 2.11.4).
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

language: scala

scala:
  - 2.11.6

jdk:
  - oraclejdk8

notifications:
  email:
    - p@pyetras.com

before_script:
  - wget https://github.com/pyetras/relaks/raw/master/lib/drill-1.1.0-SNAPHOT.tgz -O /tmp/drill.tar.gz
  - mkdir -p $HOME/.m2/repository/org/apache/drill
  - cd $HOME/.m2/repository/org/apache/drill && tar xzf /tmp/drill.tar.gz

script:
  - cd relaks && sbt ++$TRAVIS_SCALA_VERSION clean testOnly -- -l Slowpoke

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
